name = "observable-entropy"
main = "src/index.ts"
workers_dev = true
node_compat = true
usage_model = 'unbound'
compatibility_date = "2022-05-16"

kv_namespaces = [
  { binding = "OBSERVABLE_ENTROPY", id = "6ec2d152ffd24e848d522089dd63cd3e" }
]

route = { pattern = "entropy.truestamp.com", zone_name = "truestamp.com", custom_domain = true }

